
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit Fingerprint Sensor Library@^1.4.0
    bblanchon/ArduinoJson@^6.21.0
    tzapu/WiFiManager@^2.0.16
    bounce2/Bounce2@^2.70
upload_port = /dev/cu.usbserial*  ; Update for your port
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs